language: node_js
node_js:
  - '4'
  - '6'
  - '8'

sudo: false

cache:
  directories:
  - node_modules

before_install:
  - npm config set strict-ssl false
  - npm install coveralls

after_success:
  - npm run coverage
  - npm run integration-test

before_script:
  # we only need to run eslint once per build, so let's conserve a few resources
  - 'if [ "x$TRAVIS_NODE_VERSION" = "x8" ]; then $(npm bin)/eslint .; fi'

git:
  depth: 1
